version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      # Corrigido: Sobe um nível (../) para encontrar as pastas na raiz do projeto
      - ../datasets:/docker-entrypoint-initdb.d
      - ../init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    env_file:
      - .env

  backend:
    build:
      context: ./
      args:
        - BACKEND_PORT=${BACKEND_PORT}
        - DATABASE=${DATABASE}
        - MONGO_PORT=${MONGO_PORT}
    container_name: backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongodb
    command: ["npm", "start"]

networks:
  default:
    driver: bridge